feat+style : 홈 배너 작업 + 컬러 가이드 세팅
Ward-Group/Ward_iOS pull request #25
Opened 2024-05-22 13:13 UTC by SuniDev

# 작업 내용
- 홈 배너 UI 작업 진행 중
- 타이틀 폰트 전역 설정 추가
- 컬러 추가

# 관련 이슈
#19, #20 

# 참고 사항
- https://github.com/Ward-Group/Ward_iOS/pull/24 PR 관련 브렌치에서 풀받아 작업하였습니다. 해당 PR 완료 후 Filse Changed 확인하시면 됩니다.
- 피그마 기반 Color 가이드를 추가하였습니다. 저번에 회의한 Color를 네이티브에서 임의로 추가할 떄에는 #19 이슈에 작성하는 것이 좋을 것 같습니다. 작업 전 꼭 확인해주세요.

2024-05-23 09:58 UTC, peppermint100 commented on WardApp/WardApp/Presentation/Home/HomeView.swift
body를 깔끔하게 보기 위해 extension을 이용하는 경우를 저도 많이 봤는데요

https://github.com/peppermint100/swiftui-walkthrough/blob/master/TakeHomeProject/TakeHomeProject/Features/Create/Views/CreateView.swift

함수로 만드는 것 보다 계산 프로퍼티로 사용하는게 조금 더 깔끔하고 직관적이라는 느낌이 드는데 어떠신가요??

2024-05-23 10:00 UTC, peppermint100 commented on WardApp/WardApp/Support/Extensions/Font.swift
모든 폰트를 뷰모디파이어로 관리하는거 되게 좋은 것 같습니다!! 네이밍만 잘 정해서 폰트, size, weight를 여기서 쭉 관리하는 식으로 하면 좋을 것 같아요

2024-05-23 10:02 UTC, peppermint100 commented
컬러 가이드는 피그마에 있는대로 다 세팅이 된 것 같은데, 혹시 추가로 전달하실 사항이 있으셨을까요???

2024-05-23 10:04 UTC, peppermint100 commented on WardApp/WardApp/Presentation/Navigation/HeaderNavBarView.swift
피그마를 전체적으로 보니 네비게이션 바가 같은 리소스(와드 이미지, 돋보기, 사람 아이콘 등..)을 이용해서 다양한 형태가 있는 것 같은데요, 공통 모듈로 개발해야할까요..?

2024-05-23 11:14 UTC, SuniDev commented on WardApp/WardApp/Presentation/Home/HomeView.swift
좋은 생각입니다. 수정 후 PR 올릴게요.

2024-05-27 00:41 UTC, peppermint100 requested changes
- 프로젝트 파일에 컨플릭트가 있습니다. 이전거는 제가 제거에 맞게 수정해서 승인 후 머지했습니다.
- 함수형태의 뷰 -> 계산 프로퍼티 형태의 뷰가 적용되지 않은 것으로 보입니다!
- PR 라인수를 저희가 500정도로 하긴했는데, 500라인을 넘으면 자르고 500 이하면 자유롭게 ㅎ나느게 어떨까요? 홈 배너 작업과 컬러가이드는 나뉘어도 좋을 것 같습니다! (둘다 각각 200라인씩만 작성되더라도..)

2024-05-27 03:03 UTC, SuniDev commented on WardApp/WardApp/Presentation/Navigation/HeaderNavBarView.swift
제가 생각한 공통 헤더는
1. 홈에서 사용되는 로고가 포함된 헤더
2. 서브 페이지에서 쓰는 뒤로가기 헤더
생각하고 있습니다.

헤더를 공통으로 쓰는 이유는..  뒤로가기와 같은 기능은 동일한 액션을 취하기 때문에 모듈로 작업하는 것이 좋다고 생각합니다!

2024-05-27 12:13 UTC, peppermint100 requested changes
변경사항 커밋하시고 다시 한번 리퀘스트 해주세요!

2024-05-28 05:31 UTC, peppermint100 approved these changes
LGTM!

2024-05-28 05:55 UTC, merged